name: Run Flask Server

on: workflow_dispatch

jobs:
  run-flask:
    runs-on: self-hosted # Use your self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create virtual environment
        run: python3 -m venv .venv

      - name: Install dependencies
        run: |
          .venv/bin/pip install -r requirements.txt

      - name: Run Flask Server
        run: .venv/bin/python WeatherStationDataServer.py # Replace with your command to start Flask
